### ISSUE TITLE
Sockets paradigm

### ISSUE THREAD

**Issue by xyrox2** [sane/sane#169]
Hey guys,

first of all great work with the sane stack.

My problem is to understand how the sockets works. My question is how i can get a custom function in a custom class work. I want, if sockets fireing e.g. on user model, to trigger a custom function in sails. I tried it with init function but it seems not to work. So how can i do it? Its very helpfull if i need to trigger algorithms on observer or send emails if user register.
Will be great if someone can give a tutorial for the logic behind sockets worker. I think im not the only one :)

**Comment by Master244** [comment]
first google hit :), http://stackoverflow.com/questions/27189483/where-did-the-sailsjs-websockets-documentation-go

**Comment by jamemackson** [comment]
Thanks @Master244, as that SO post show's, it looks like the sails sockets documentation has moved and google hasn't necessarily caught up but it's here: http://sailsjs.org/documentation/reference/web-sockets

Also, @xyrox2, I dont know if this is still something you're looking at since you're issue was opened so long ago but you can checkout a quick and dirty example I put together a while back [(jamemackson/example-sane-realtime)](https://github.com/jamemackson/example-sane-realtime) and specifically here [where the sockets get wired up](https://github.com/jamemackson/example-sane-realtime/blob/master/client/app/components/activity-list.js#L4-L15) on the client side.  

Keep in mind that this is a super quick proof of concept example, I wouldn't necessarily architect it the way it is shown here but it should give you some ideas.
